#!/usr/bin/env node
// Appends one datapoint to data/history.js from whatever the syncs have
// most recently written.
//
// Every other sync overwrites its file, so nothing in this repo had a time
// series — which is why the Overview trends panel had nothing to draw. This
// runs after the syncs and accumulates one sample per run.
//
// Samples are trimmed to RETAIN_DAYS so the file cannot grow without bound;
// at hourly collection that is a few hundred rows, which stays small enough
// to ship as a plain script tag.

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const RETAIN_DAYS = 30;

// Each data file is a plain `const NAME = {...}` script, so it is read and
// evaluated rather than parsed — same approach the other scripts use.
function loadConst(file, name) {
  const p = path.join(ROOT, "data", file);
  if (!fs.existsSync(p)) return null;
  try {
    return new Function(`${fs.readFileSync(p, "utf8")}; return ${name};`)();
  } catch (e) {
    console.log(`could not read ${file}: ${e.message}`);
    return null;
  }
}

function main() {
  const status = loadConst("status.js", "DEVICE_STATUS");
  const wireless = loadConst("wireless.js", "WIRELESS");
  const endpoints = loadConst("endpoints.js", "ENDPOINT_SUMMARY");
  const security = loadConst("security.js", "SECURITY_SUMMARY");
  const tickets = loadConst("tickets.js", "TICKET_SUMMARY");

  const devices = Object.values(status?.devices || {});
  const apCounts = wireless?.counts || {};

  // null, not 0, when a feed has not reported — a missing sample must not be
  // plotted as a real drop to zero.
  const sample = {
    at: new Date().toISOString(),
    devicesUp: devices.length ? devices.filter((d) => d.status === "up").length : null,
    devicesDown: devices.length ? devices.filter((d) => d.status === "down").length : null,
    apsUp: apCounts.up ?? null,
    apsDown: wireless ? (apCounts.down ?? 0) + (apCounts.warning ?? 0) : null,
    endpointsOnline: endpoints?.devices?.online ?? null,
    endpointAlerts: endpoints?.alerts?.total ?? null,
    securityOpen: security?.open ?? null,
    ticketsOpen: tickets?.open ?? null,
    ticketsUrgent: tickets?.urgent ?? null,
  };

  const existing = loadConst("history.js", "HISTORY") || { samples: [] };
  const cutoff = Date.now() - RETAIN_DAYS * 86400000;
  const samples = [...(existing.samples || []), sample]
    .filter((s) => Date.parse(s.at) >= cutoff)
    .sort((a, b) => Date.parse(a.at) - Date.parse(b.at));

  const payload = { updatedAt: sample.at, retainDays: RETAIN_DAYS, samples };

  const banner = [
    "// Rolling history — one sample per collection run.",
    "// Generated by .github/workflows/collect-history.yml — do not edit by hand.",
    "//",
    "// Counts only, sampled from the other data files after they sync. A field",
    "// is null when that feed had not reported, so a gap is never plotted as a",
    `// real drop to zero. Trimmed to the last ${RETAIN_DAYS} days.`,
  ].join("\n");

  fs.writeFileSync(
    path.join(ROOT, "data/history.js"),
    `${banner}\nconst HISTORY = ${JSON.stringify(payload, null, 2)};\n`
  );

  const span = samples.length > 1
    ? ((Date.parse(samples.at(-1).at) - Date.parse(samples[0].at)) / 3600000).toFixed(1) + " h"
    : "first sample";
  console.log(`wrote data/history.js — ${samples.length} samples spanning ${span}`);
  console.log(`  ${JSON.stringify(sample)}`);
}

main();
